USE [master]
GO

CREATE DATABASE [BolfTracker] ON  PRIMARY 
( NAME = N'BolfTracker', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\BolfTracker.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BolfTracker_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\BolfTracker_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BolfTracker] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BolfTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BolfTracker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BolfTracker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BolfTracker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BolfTracker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BolfTracker] SET ARITHABORT OFF 
GO

ALTER DATABASE [BolfTracker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BolfTracker] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BolfTracker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BolfTracker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BolfTracker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BolfTracker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BolfTracker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BolfTracker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BolfTracker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BolfTracker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BolfTracker] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BolfTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BolfTracker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BolfTracker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BolfTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BolfTracker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BolfTracker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BolfTracker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BolfTracker] SET  READ_WRITE 
GO

ALTER DATABASE [BolfTracker] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BolfTracker] SET  MULTI_USER 
GO

ALTER DATABASE [BolfTracker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BolfTracker] SET DB_CHAINING OFF 
GO